'use strict';
module.exports = {
  plugins: ['react'],
  parserOptions: {
    ecmaFeatures: { jsx: true },
  },
  rules: {
    'react/display-name': 'off',
    'react/forbid-prop-types': 'off',
    'react/no-danger': 'off',
    'react/no-deprecated': 'warn',
    'react/no-did-mount-set-state': ['warn'],
    'react/no-did-update-set-state': ['warn'],
    'react/no-direct-mutation-state': 'warn',
    'react/no-is-mounted': 'warn',
    'react/no-multi-comp': 'off',
    'react/no-set-state': 'off',
    'react/no-string-refs': 'off',
    'react/no-unknown-property': 'warn',
    'react/prefer-es6-class': 'warn',
    'react/prefer-stateless-function': 'off',
    'react/prop-types': 'off',
    'react/react-in-jsx-scope': 'warn',
    'react/self-closing-comp': 'warn',
    'react/sort-comp': 'off',
    'react/sort-prop-types': 'off',
    'react/wrap-multilines': 'off',
    'react/jsx-boolean-value': ['warn', 'always'],
    'react/jsx-closing-bracket-location': 'off',
    'react/jsx-curly-spacing': 'warn',
    'react/jsx-equals-spacing': 'warn',
    'react/jsx-handler-names': 'off',
    'react/jsx-indent-props': ['warn', 2],
    'react/jsx-indent': ['warn', 2],
    'react/jsx-key': 'warn',
    'react/jsx-max-props-per-line': 'off',
    'react/jsx-no-bind': 'off',
    'react/jsx-no-duplicate-props': 'warn',
    'react/jsx-no-literals': 'off',
    'react/jsx-no-undef': 'warn',
    'react/jsx-pascal-case': 'warn',
    'react/jsx-sort-props': 'off',
    'react/jsx-space-before-closing': 'warn',
    'react/jsx-uses-react': 'warn',
    'react/jsx-uses-vars': 'warn',
  },
};
